spambot.settings:
  type: mapping
  label: Settings
  mapping:
    spambot_whitelist_email:
      type: string
    spambot_whitelist_username:
      type: string
    spambot_whitelist_ip:
      type: string
    spambot_user_register_protect:
      type: boolean
    spambot_check_blocked_accounts:
      type: boolean
    spambot_last_checked_uid:
      type: integer
    spambot_log_blocked_registration:
      type: boolean
    spambot_sfs_api_key:
      type: boolean
    spambot_blocked_message:
      type: boolean
